nbcamp-archive/kkuk-ios

Kkuk.xcodeproj/project.pbxproj, Kkuk/Global/Extension/UIColor.swift, Kkuk/Resource/Assets.xcassets/Colors/Contents.json, Kkuk/Resource/Assets.xcassets/Colors/background.colorset/Contents.json, Kkuk/Resource/Assets.xcassets/Colors/main.colorset/Contents.json, Kkuk/Resource/Assets.xcassets/Colors/subgray1.colorset/Contents.json, Kkuk/Resource/Assets.xcassets/Colors/subgray2.colorset/Contents.json, Kkuk/Resource/Assets.xcassets/Colors/subgray3.colorset/Contents.json, Kkuk/Resource/Assets.xcassets/Colors/text1.colorset/Contents.json
=> [PR] feature/KK-12

Kkuk.xcodeproj/project.pbxproj, Kkuk/Presentation/AddContent/Component/.gitkeep, Kkuk/Presentation/AddContent/Component/AddContentButton.swift, Kkuk/Presentation/AddContent/View/AddContentViewController.swift
=> [PR] design/KK-17

Kkuk.xcodeproj/project.pbxproj, Kkuk/Presentation/SearchContent/Component/.gitkeep, Kkuk/Presentation/SearchContent/Component/ContentTableViewCell.swift, Kkuk/Presentation/SearchContent/Component/RecentSearchContentCollectionViewCell.swift, Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift, Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
=> [PR] design/KK-19

Kkuk/Presentation/AppInfo/Component/SettingItemCell.swift, Kkuk/Presentation/AppInfo/View/AppInfoViewController.swift
=> [PR] design/KK-48

Kkuk.xcodeproj/project.pbxproj, Kkuk/Global/Component/CompleteButton.swift, Kkuk/Global/Component/InduceLabel.swift, Kkuk/Presentation/AddContent/Component/SetCategoryCell.swift, Kkuk/Presentation/AddContent/View/AddContentViewController.swift, Kkuk/Resource/Assets.xcassets/Colors/text1.colorset/Contents.json
- 이곳을 수정해서 연결된 작업 또는 이슈를 명시해주세요.
- 예시: #1, #2, #3
=> [PR] basic/KK-60

Kkuk/Application/AppDelegate.swift, Kkuk/Core/Manager/ContentManager.swift, Kkuk/Core/Model/ContentModel.swift, Kkuk/Presentation/Category/Component/CategoryCollectionViewCell.swift, Kkuk/Presentation/Category/View/CategoryInnerViewController.swift, Kkuk/Presentation/Category/View/CategoryViewController.swift, Kkuk/Service/RealmCategoryService.swift
=> [PR] feature/KK-61

Kkuk/Core/Manager/ContentManager.swift, Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift, Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
=> [PR] feature/KK-64

Kkuk/Core/Model/ContentModel.swift, Kkuk/Presentation/AddContent/View/AddContentViewController.swift
=> [PR] feature/KK-67 

Kkuk/Presentation/Category/View/CategoryInnerViewController.swift, Kkuk/Presentation/Home/View/HomeViewController.swift, Kkuk/Presentation/SearchContent/Component/ContentTableViewCell.swift, Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
=> [PR] feature/KK-50

Kkuk/Presentation/SearchContent/Component/RecentSearchContentCollectionViewCell.swift, Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift, Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
=> [PR] design/KK-78

Kkuk/Presentation/AppInfo/Component/SettingItemCell.swift, Kkuk/Presentation/AppInfo/View/AppInfoViewController.swift, Kkuk/Presentation/Category/View/AddCategoryViewController.swift
=> [PR] design/KK-76

Kkuk.xcodeproj/project.pbxproj, Kkuk/Global/Enum/Asset.swift, Kkuk/Presentation/Category/Component/CategoryTableViewCell.swift, Kkuk/Presentation/Setting/Component/SettingItemCell.swift, Kkuk/Presentation/Setting/View/SettingViewController.swift
=> [PR] design/KK-115

Kkuk.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Kkuk/Presentation/Category/Component/CategoryTableViewCell.swift, Kkuk/Presentation/Category/View/EditCategoryViewController.swift
=> [PR] refactor/KK-132

Kkuk/Application/SceneDelegate.swift
- #141 
- 미분류 카테고리 아이콘이 아직 없어서 추가해야할 것 같습니다.
=> [PR] feature/KK-141

Kkuk/Presentation/Home/Component/BookmarkCell.swift, Kkuk/Presentation/Home/View/HomeViewController.swift
=> [PR] refactor/KK-144

Kkuk/Presentation/AddContent/View/AddContentViewController.swift, Kkuk/Presentation/Category/View/AddCategoryViewController.swift, Kkuk/Presentation/Category/View/CategoryInnerViewController.swift, Kkuk/Presentation/Category/View/CategoryViewController.swift, Kkuk/Presentation/Home/View/HomeViewController.swift, Kkuk/Presentation/PanModal/PanModalTableViewController.swift, Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift, KkukShareExtension/View/AddContentShareViewController.swift
=> [PR]refactor/KK-55

Kkuk/Presentation/AddContent/View/AddContentViewController.swift, Kkuk/Presentation/Category/View/AddCategoryViewController.swift
=> [PR] refactor/KK-160

Kkuk/Presentation/Category/View/AddCategoryViewController.swift, Kkuk/Presentation/Category/View/CategoryInnerViewController.swift, Kkuk/Presentation/Category/View/CategoryViewController.swift, Kkuk/Presentation/Home/View/HomeViewController.swift
=> [PR] design/KK-158

Kkuk/Presentation/Category/Component/AddCategoryIconCollectionViewCell.swift
=> [PR] design/KK-167

Kkuk/Presentation/Category/View/CategoryInnerViewController.swift, Kkuk/Presentation/Home/View/HomeViewController.swift, Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
=> [PR] feature/KK-165
